### Signup
POST http://localhost:5000/signup
Content-Type: application/json

{
  "name": "Fagun",
  "email": "fagun@example.com",
  "password": "12345"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fagun@example.com",
  "password": "12345"
}

### Refresh (paste refreshToken from /login)
POST http://localhost:5000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJmYWd1bkBleGFtcGxlLmNvbSIsImlhdCI6MTc1NjM2ODIyMiwiZXhwIjoxNzU2OTczMDIyfQ.-aFVUjO7v9w4sjUERCHrBWCmBuZbtGu7YCpf0N7qopU"
}

### Protected route (paste access token into Authorization)
GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJmYWd1bkBleGFtcGxlLmNvbSIsImlhdCI6MTc1NjM2ODI0OSwiZXhwIjoxNzU2MzY5MTQ5fQ.klBoRfIAYnAzma21uCgWo32BmcjGQSZyUaQFIqc33Sw
### Logout (invalidate refresh token)
POST http://localhost:5000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2Mjg4NTYwLCJleHAiOjE3NTY4OTMzNjB9.E4OxjN8JpgRsoME1Gc9cma4wcHGL69PO8ICOO7Ieyhw"
}
